version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart_resips
    ports:
      - "8002:10000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d0krj4ggjchc73ej5n50-a.singapore-postgres.render.com:5432/recipe_o3z7
      SPRING_DATASOURCE_USERNAME: recipe_o3z7_user
      SPRING_DATASOURCE_PASSWORD: kfYWFMYHEZJ3nBR2S7Wj7IcPyUqIRaI5
      SERVER_PORT: 10000
